[default]
src = 'src'
out = 'out'
libs = ['lib']
# Override the Solidity version (this overrides `auto_detect_solc`)
#solc_version = '0.8.10'
# Whether or not Forge should auto-detect the solc version to use
#auto_detect_solc = true
# Print the names of the compiled contracts
names = true
# Print the sizes of the compiled contracts
sizes = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config